### ISSUE TITLE
Radiobutton / Radio issue in array

### ISSUE THREAD

**Issue by jainashwin** [json-schema-form/angular-schema-form#567] opened 2015-10-03 11:45 UTC
Radiobutton and raio doesn't seem to work correctly while being part of an array. Model doesn't reflect the values of selected option. Also radio button let user select multiple values (like checkboxes).

Here is sample form and schema - 
Schema - 

```
vm.sSchema={    "type":"object",
    "properties":{
        "field1":{"type":"array",
            "items":{"type":"object",
                "properties":{
                    "field":{"type":"string",
                        "title":"Radio Example",
                        "enum":["valA","valB","valC"]
                    }
                }
            }
        }
    }
};
```

And here is form definition - 

```
vm.sForm=[
    {
        key:"field1",
        add:null,
        notitle:true,
        items:[
        {
            key:"field1[].field",
            type: "radiobuttons",
            titleMap: [
              { value: "valA", name: "Value A" },
              { value: "valB", name: "Value B" },
              { value: "valC", name: "Value C" }
            ]
        }
        ]
    }
];
```

**Comment by franklopez** [comment] 2015-10-12 15:36
same problem here.

**Comment by mpina83** [comment] 2015-10-13 09:07
I'm currently having the same issue for any type of radio buttons inside an array when using the angular schema form bootstrap (bootstrap-decorator.js). The problem is I cant revert into the older bootstrap decorator because the destroyStrategy isnt working properly inside arrays in the older version. Altho any radio field types work in the older version without any issue

**Comment by darrencrossley** [comment] 2015-10-25 16:30
Same here - This is quite a big problem for me - any radio buttons inside an array don't get stored to the model. Also using the bootstrap decorator if it helps...

**Comment by Anthropic** [comment] 2016-04-11 04:54
@jainashwin @franklopez @mpina83 @darrencrossley can any of you create a Gist with a demo of the behaviour for us please?

**Comment by jainashwin** [comment] 2016-04-15 13:49
http://embed.plnkr.co/pPHGOy/

PS  :Somehow this plunkr works only with FF but not with Chrome

**Comment by jainashwin** [comment] 2016-04-21 16:33
Done.

**Comment by s-a-85** [comment] 2016-07-08 16:26
I'm having the same issue. Does anyone have any ideas about what is causing this? Thanks.

**Comment by raquintero** [comment] 2016-10-31 19:15
This is still an issue, and I did the updated fix for Buttons to have access to the index, so I'm assuming that radio buttons are not really "buttons"?  Any overall fix, roadmap, idea, or how to handle arrays and arrays in arrays, holistically?  Every "fix" seems to be piece meal, and never makes it into a release build.  Is there a real roadmap, or is the focus really just moving to Angular 2 and Material?  Honest question.

**Comment by Anthropic** [comment] 2016-11-01 13:12
@raquintero more a case of one person trying to deal with 140+ GitHub issues to get back on top of them in his spare time.

If I don't face the issue in my work it is hard to give it the priority it needs, for now, at the same time I am trying to finish off a re-write started by the former maintainer. I am starting to get further with that recently thankfully (webpack-babel branch).

@jainashwin as far as I can tell, changing the template from **item in form.titleMap** to **tm in form.titleMap** and updating other item references in the templates seems like it fixes the issue for me. I will do some more testing and try to provide a patch to the decorator soon.

The cause is **item.value === $$value$$** in the templates is mixing up item data with titleMap data.

**Comment by s-a-85** [comment] 2016-11-01 13:32
@Anthropic Thanks a lot for your response. Will give it a go.

**Comment by raquintero** [comment] 2016-11-02 15:10
@Anthropic Thanks for the response, I will give a look.
Quick question, when you say you tested in in the templates, which version of the templates (bootstrap-schema.js) are you referring to?  I want to make sure I test with the same exact copy you worked from.

Also, I would love to help out with the work that needs to be done.  I don't have a lot of free time as well, but if there is a good "Deep-dive" into the actual code bases, as a System, and not just the high level architecture, it would help myself, or others be able to target exactly the areas of responsibility and dependencies of the overall "ASF" ecosystem.  
Again, I would love to be able to help and contribute.

**Comment by Anthropic** [comment] 2016-11-03 03:11
@raquintero message me on Gitter, I am happy to help you get up to speed on what is going on :)

https://github.com/json-schema-form/angular-schema-form/tree/feature/webpack-babel/dist
schema-form.js
angular-schema-form-bootstrap.js

The whole example folder in that branch should work as a starting point.

**Comment by Anthropic** [comment] 2017-02-27 12:57
The templates were updated for the alpha releases.

Please re-open if the issue persists in the alphas.

**Closed by Anthropic** 2017-02-27 12:57 UTC
Labels: has: solution / suggestion, migrated: to webpack, type: bug
