### ISSUE TITLE
Pure TV4 validation vs. ASF+TV4 Validation

### ISSUE THREAD

**Issue by souluniversal** [json-schema-form/angular-schema-form#436] opened 2015-06-18 16:10 UTC
Hi again! Looking for some advice about TV4 validation  +/- ASF. This is for a Canadian PostalCode below. Pure TV4 validation runs as per below. PostalCode,  though not required per schema, when empty string on instance, fails as it does not match the pattern... (and see other examples below)... I suppose, this is solid and correct behavior on the part of TV4.

However... this is not the same behavior implemented by ASF + TV4, which will allow/validate data1... Not familiar with the inners of ASF, but my guess would be that ASF doesn't bother running TV4 validation on the subschema for the PostalCode value strings that are empty if it is not "required". Should ASF just DELETE such values from the model  instead, and still run TV4?... 

Just now re-looking at the pictures (pasted below) and looking at the bad behavior of the model... NO VALUE (i.e. deleted) on model when invalid to pattern value coming from form (correct behavior) . VALUE STILL ON MODEL when value on form is empty (incorrect behavior) .

##Example Script (can just run in browser with TV4 or ASF)

```javascript
var data1 = {
    "PostalCode":""
}

var data2 = {
    "PostalCode": undefined
}

var data3 = {

}


var schema = {
    type:"object",
    properties:{
        "PostalCode": {
            "type": "string"

            ,"maxLength": 6

            ,pattern:'[ABCEGHJKLMNPRSTVXYabceghjklmnprstvxy][0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz] ?[0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz][0-9]'

        }
    }
};


console.log(tv4.validate(data1, schema)); 
console.log( JSON.stringify(tv4.error, null, 4)); 

console.log(tv4.validate(data2, schema));)
console.log( JSON.stringify(tv4.error, null, 4));

console.log(tv4.validate(data3, schema)); 
console.log( JSON.stringify(tv4.error, null, 4)); 
```

##Output

```javascript
false
{
    "message": "String does not match pattern: [ABCEGHJKLMNPRSTVXYabceghjklmnprstvxy][0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz] ?[0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz][0-9]",
    "params": {
        "pattern": "[ABCEGHJKLMNPRSTVXYabceghjklmnprstvxy][0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz] ?[0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz][0-9]"
    },
    "code": 202,
    "dataPath": "/PostalCode",
    "schemaPath": "/properties/PostalCode/pattern",
    "subErrors": null,
    "stack": "Error: String does not match pattern: [ABCEGHJKLMNPRSTVXYabceghjklmnprstvxy][0-9]..."
}
false
{
    "message": "Invalid type: undefined (expected string)",
    "params": {
        "type": "undefined",
        "expected": "string"
    },
    "code": 0,
    "dataPath": "/PostalCode",
    "schemaPath": "/properties/PostalCode/type",
    "subErrors": null,
    "stack": "Error: Invalid type: undefined (expected string)..."
}
true
null

``` 
## Here is the technically incorrect behavior, pictured using the example page
![image](https://cloud.githubusercontent.com/assets/2290379/8236248/1c075f30-15b5-11e5-9884-18d4b71bce8f.png)

![image](https://cloud.githubusercontent.com/assets/2290379/8236252/2236535c-15b5-11e5-9c43-f67ff1b3d343.png)

## Here is the behavior, pictured using the example page, with required added
![image](https://cloud.githubusercontent.com/assets/2290379/8236242/139c7e66-15b5-11e5-893e-807bcc17ba2e.png)

**Comment by davidlgj** [comment] 2015-06-30 07:58
hi @souluniversal,

by design schema form only validates the fields that are actually in the form, it does not do a "whole" object valdiation with tv4. This is since we want to support forms that use a small part of a schema. 

It will also only validate when changed from the form. Any starting model value is therefor regarded as valid from the start. To validate initial values directly issue a `schemaFormValidate` event. 

Otherwise I'm not sure that I totally follow, can you give me some steps to reproduce and expected behaviour?

**Comment by nicklasb** [comment] 2016-04-10 00:07
No answer, closing.
Please re-open if you do not feel the question has been answered sufficiently.

**Closed by nicklasb** 2016-04-10 00:07 UTC
Labels: needs: review
