### ISSUE TITLE
Checkbox in form error

### ISSUE THREAD

**Issue by JonFir** [json-schema-form/angular-schema-form#558] opened 2015-09-28 19:36 UTC
Hello!
I try add checkbox to form
```javascript
{
    "key": "modules.bindadm",
    "type": "checkbox",
    "value": "dsadsa",
    "title": "Будет установлен модуль управления почтовым сервером"
}
```
and take error `Error: undefined is not an object (evaluating 'obj.schema['default'])'`

I inspect source code, and find this section:
```javascript
if (obj.type === 'checkbox' && angular.isUndefined(obj.schema['default'])) {
   obj.schema['default'] = false;
}
```
You try determinate `obj.schema['default']`, but `obj` not have property `schema`:
```javascript
[Log] Object (schema-form.js, line 1463)
key: Array[2]
title: "Будет установлен модуль управления почтовым сервером"
type: "checkbox"
value: "dsadsa"
__proto__: Object
```
My js skill very low) but i try change you code like:
```javascript
if (obj.type === 'checkbox' && angular.isUndefined(obj.schema)) {
    obj.schema = ['default'];
    obj.schema['default'] = false;
}
```
This code work, but i don't know, may be its bad solution.

And i have answer question. Can i add value to checkbox. In default, checkbox can be `true` or `false`, but i need, add string value, like 'some string', its possible?
P.S.: Sorry my low english skill.
Regards.

**Comment by vinceis1337** [comment] 2015-11-13 02:24
@davidlgj can you or someone else take a look at this? I'm having the same issue:
<img width="953" alt="screen shot 2015-11-12 at 8 20 50 pm" src="https://cloud.githubusercontent.com/assets/5994871/11137229/4dd0dd90-897b-11e5-9ae1-37923caa8b13.png">

Which is definitely from this code.

**Comment by sgarbesi** [comment] 2016-03-08 18:10
+1

**Comment by Anthropic** [comment] 2016-04-11 05:11
@JonFir @vinceis1337 @sgarbesi if anyone can put together a gist/plunker/demo that would be a great help?

**Comment by vinceis1337** [comment] 2016-04-11 08:43
@Anthropic I don't remember how exactly I got this problem but I can tell you why it is happening.

The issue is that `obj.schema` ITSELF is undefined, my guess is because we self-define the checkbox (inside of $scope.form) instead of generating it from a schema. 

This means that inherently, the checkbox has no reference data from the schema, therefore it logically has no schema property.

Therefore, the check `angular.isUndefined(obj.schema['default']))` fails as it is attempting to read a child property when the parent does not exist.

I believe the proper fix is to first check whether obj.schema exists as follows:

```
//check if object is a checkbox
if (obj.type === 'checkbox') {
  //check if obj has a schema
  if (angular.isUndefined(obj.schema) {
    //if it doesn't, add a schema definition that consists only of a default state of false
    obj.schema = { default: false };
  }
  //if object has a schema, check if the default state is defined
  else if (angular.isUndefined(obj.schema['default'])) {
    //if it is not defined, define it as false
    obj.schema['default'] = false;
  }
}
```

Please note that this logic occurs in two places: `src/services/schema-form.js` and `dist/schema-form.js`. I don't know if they are synchronized but you may have to change it in both places.

[Search results here.](https://github.com/json-schema-form/angular-schema-form/search?utf8=%E2%9C%93&q=if+%28obj.type+%3D%3D%3D+%27checkbox%27+%26%26+angular.isUndefined%28obj.schema%5B%27default%27%5D%29%29&type=Code)

**Comment by Anthropic** [comment] 2016-04-11 08:50
@vinceis1337 the dist folder is the built files, so that is fine.

What happens if you have a default value on the form definition, is that not enough to avoid the issue?

**Comment by vinceis1337** [comment] 2016-04-11 08:56
@Anthropic I am not sure what you mean.

If you mean setting `value` to true or false, it doesn't appear to fix it issue. 
Gist: http://schemaform.io/examples/bootstrap-example.html#/69195a23f9eab268bcc2208cdbae22b4

If you mean setting a `default` key, that doesn't appear to be defined in the documentation. Also it doesn't work either.
Gist: http://schemaform.io/examples/bootstrap-example.html#/ee581d1abd7a47d76745798041758d0d

**Comment by Anthropic** [comment] 2016-04-11 09:05
Thanks @vinceis1337 appreciate your help, will need to re-visit this once the new core is split out from this repo to json-schema-form-core.

**Comment by vinceis1337** [comment] 2016-04-11 09:09
@Anthropic sure, I can make a pull request. I'll need 10 minutes.

**Comment by Anthropic** [comment] 2016-04-11 09:18
@vinceis1337 that's awesome, the usual response to that question is "maybe next week". Just remember not to commit the dist folder please, and don't be concerned by the tests failing on four items, been meaning to fix them since I updated the CI tool since the repo changed location :)

**Comment by vinceis1337** [comment] 2016-04-11 09:22
@Anthropic Glad to help! Angular Schema Form has been really helpful for me so I don't mind at all :).

And I was about to ask if I should gulp submitting the PR, but that answers the question. :P

**Comment by Anthropic** [comment] 2016-04-11 09:28
There is a CONTRIBUTING md ;)

**Comment by vinceis1337** [comment] 2016-04-11 09:32
Ooo I see that now. Thanks!

https://github.com/json-schema-form/angular-schema-form/pull/663 created.

**Comment by Anthropic** [comment] 2016-04-11 09:35
@vinceis1337 if you want to contribute, we are **always** looking for people to **help**, the Gitter is a good source for seeing where and when help is needed as we begin the next phase of the project since Textalk gave it up to the internets leading up to v1 :)

Closing this now as discussion can move to PR.

**Closed by Anthropic** 2016-04-11 09:35 UTC
Labels: type: bug, ui: core
