### ISSUE TITLE
RequireJs wrapper for bootstrap-decorator

### ISSUE THREAD

**Issue by artemshapovalov** [json-schema-form/angular-schema-form#435] opened 2015-06-18 11:05 UTC
Please add requirejs wrapper for bootstrap decorator. Because after concat vendor to one file Bootstrap decorator throws exception as:

```
Uncaught Error: [$injector:nomod] Module 'schemaForm' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=schemaForm
```

**Comment by angelaharalson** [comment] 2015-07-28 15:18
I'm having the same issue. Any work arounds?

**Comment by robinduckett** [comment] 2015-08-05 12:19
Really odd. Using browserify to include angular modules, schemaForm was "working" but throwing an error about not finding any decorators. This fixed it for me:
``` javascript
var schemaForm = require('angular-schema-form');
var bootstrapDecorator = require('angular-schema-form/dist/bootstrap-decorator');
```

Interestingly enough @angelaharalson I tried using your fork/commit, and nothing changed, and the above code worked.. Perhaps I'm requiring modules funny?

**Comment by nicklasb** [comment] 2016-04-10 00:06
Is this still a problem?

**Comment by gornostal** [comment] 2016-04-17 10:27
I'm seeing this problem with angular-schema-form#0.8.13

**Comment by nicklasb** [comment] 2016-04-17 10:34
Just a thought, are you using the external bootstrap decorator?
I had strange import problems that sort of magically went away when I switched to that.

(also, that is the way to use the framework, the internal one will permanently go away in 1.0)

**Comment by gornostal** [comment] 2016-04-17 10:38
Yes, I do.
First, I was confused by implicit dependency on `objectpath` and `tv4`, so I had to install them and include in a build process.
My gulpfile.js includes these files in a final build. `angular-schema-form-bootstrap/bootstrap-decorator.min.js` is among those files.
Do I do anything wrong?

```js
['bower_components/angular/angular.min.js',
 'bower_components/angular-route/angular-route.min.js',
 'bower_components/angular-ui-grid/ui-grid.js',
 'node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js',
 'node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js',
 'bower_components/angular-schema-form-bootstrap/bootstrap-decorator.min.js',
 'bower_components/angular-schema-form/dist/schema-form.min.js',
 'bower_components/objectpath/lib/ObjectPath.js',
 'bower_components/tv4/tv4.js']
```

**Comment by nicklasb** [comment] 2016-04-17 10:46
Not sure if that list implies order, but if so, this would be the correct order:
['bower_components/angular/angular.min.js',
 'bower_components/angular-route/angular-route.min.js',
 'bower_components/angular-ui-grid/ui-grid.js',
 'node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js',
 'node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js',
'bower_components/objectpath/lib/ObjectPath.js',
 'bower_components/tv4/tv4.js',
 'bower_components/angular-schema-form/dist/schema-form.min.js',
 'bower_components/angular-schema-form-bootstrap/bootstrap-decorator.min.js']

**Comment by gornostal** [comment] 2016-04-17 10:49
Ah, of course. That helped.
The root cause was that the decorator should've came **after** schema-form.min.js

Thanks a lot.

**Comment by gornostal** [comment] 2016-04-17 10:53
I'm thinking what changes are need to be made and where, so other people could figure this out faster?

Perhaps to raise an exception in bootstrap-decorator.js if module 'schemaForm' is not defined yet.
Will that work?

**Comment by nicklasb** [comment] 2016-04-17 11:07
Well, that is basically what the error message that starts off this issue, "Module 'schemaForm' is not available!" means. It is not available since it has not been loaded. At all or just not yet.
 
ASF don't know any more than angular, for example if it is not loaded at all, so ASF would have to say something similar.

Actually I would rather take the opportunity to recommend people to look into a package dependency aware module loader, like [JSPM/SystemJS](http://jspm.io/). It is like npm for the frontend and basically makes these kinds of problems go away permanently. It also has lots of other useful features.

**Comment by gornostal** [comment] 2016-04-17 11:11
Yeah, your are right about the error.
For some reason I thought it was caused by my code that uses schemaForm, but now I looked at the stack trace and see `
%7B%7Brow.entity.icon%7D%7D:1 GET http://localhost:3000/%7B%7Brow.entity.icon%7D%7D 404 (Not Found)`. All that make sense now.

**Comment by nicklasb** [comment] 2016-04-17 11:15
Ok. I am closing this now, as the others haven't responded. 
Feel free to reopen if any in here thought that was premature.

For posterity, it should be emphasised that it is important to load the decorators *after* angular-schema-form itself.

**Closed by nicklasb** 2016-04-17 11:15 UTC
