### ISSUE TITLE
0.8.13 - issue with condition logic on IE.

### ISSUE THREAD

**Issue by Deklin** [json-schema-form/angular-schema-form#903] opened 2017-06-20 18:11 UTC
#### Expected behaviour
I expected the condition logic to not fail on IE

#### Actual behaviour
It actually fails on IE, however you have it fixed in master, I've created a fork and fixed it against 0.8.13 to give you an 0.8.14 however I have no way to PR this properly.

#### Gist/Plunker/Demo

[Description](url)

#### Related issues
Please review this PR, this is a port back of your fix on the development branch back to something compatible with 0.8.13 in hopes to get an 0.8.14.

https://github.com/Deklin/angular-schema-form/tree/0.8.14

@json-schema-form/angular-schema-form-lead

**Comment by Deklin** [comment] 2017-06-20 18:11
I have no target branch to PR against for you to see the change,  But the changes are limited to only what was fixed on the development branch for the builder.condition method.

**Comment by Anthropic** [comment] 2017-06-21 00:36
@Deklin try targeting the **support/0.x** branch, that should be the closest to 0.8.13

**Comment by rhelgeby** [comment] 2018-01-30 11:09
I see that this is merged into support/0.x, but is it released? As far as I can see 0.8.13 is still the latest release.

Is there any chance to get an updated build of dist/schema-form.js that I can reference until the release is ready?

**Comment by Anthropic** [comment] 2018-02-06 05:03
@rhelgeby the alphas are fairly stable, you could try them, or just pull the change from the 0.x branch. I made a 0.x branch primarily to keep track of that version as it is in use and the new versions are so different internally.

**Comment by rhelgeby** [comment] 2018-02-06 14:29
Unfortunately I can't take that risk at the moment, but referencing the 0.8.13 branch is ok. Though the build in the dist-folder on that branch is outdated.

Would you mind doing a new build and commit it on that branch? Then I can use a github link in my package.json file.

**Comment by Anthropic** [comment] 2018-02-07 00:14
@rhelgeby could you run the build and confirm it works? I'm in the middle of work on another branch, but I would totally accept a PR for that branch that has just run the build. If not then I will try to find time this weekend.

**Comment by rhelgeby** [comment] 2018-02-07 21:29
I plan to fork and create a pull request with the updated build soon. Then I should be able to verify this specific fix, and do some regression testing of the features the app is using.

**Comment by rhelgeby** [comment] 2018-02-19 12:52
Although the build server couldn't build it, the build I provided in the pull request works for me (the IE bug is fixed). So far it seems good, and I since this is going in production in a few months, I will notify if there are any issues blocking it.

Currently I'm referencing the branch in my fork so that any changes doesn't mess with the release schedule for the app.

**Comment by Anthropic** [comment] 2018-02-22 00:13
@rhelgeby ignore the travis build on that branch, before I started on the project the tests were broken and I only fixed them all for the alphas. One of the reasons I am terrified to touch that older code frankly.

**Comment by Anthropic** [comment] 2018-08-08 12:18
I believe this is closed by @rhelgeby 's merged PR, if not let me know what else is needed

**Closed by Anthropic** 2018-08-08 12:18 UTC
Labels: needs: work
