### ISSUE TITLE
Feasibility to integrate Angular-UI's Datepicker & Timepicker

### ISSUE THREAD

**Issue by benoror** [json-schema-form/angular-schema-form#355] opened 2015-04-16 15:33 UTC
Datepicker: http://angular-ui.github.io/bootstrap/#/datepicker
Timepicker: http://angular-ui.github.io/bootstrap/#/timepicker

* Is there a straightforward way to use them with **schema-form**?
* Or should I consider developing 3rd party extensions?
* **Would anyone be interested?**

**Comment by Dervisevic** [comment] 2015-04-16 15:36
No straight forward way of using them except building an addon. As for interest, depends on if one doesn't find [this](https://github.com/Textalk/angular-schema-form-datepicker) meets their requirements. The timepicker part of pickadate.js hasn't been implemented in the addon, as we had no need for it.

So it's up to what you feel :)

**Comment by davidlgj** [comment] 2015-04-17 13:13
@benoror you can always try out just using the `template` form field type, but anything that plays nice with `ng-model` should be easy to do a add-on off, basically you just need a template in that case. But we love to see new add-ons!

**Comment by brettahale** [comment] 2015-05-19 19:13
This is quick and dirty for what I needed but can be build upon. Use how ever you would like. https://gist.github.com/brettahale/5fe67b3ea3de915537e0

**Comment by davidlgj** [comment] 2015-05-19 20:00
Thanks for sharing @brettahale!

**Comment by benoror** [comment] 2015-05-19 21:54
Thanks @brettahale !

**Comment by Anthropic** [comment] 2016-04-11 09:23
@brettahale @benoror it would be great to see this as an add-on if it progressed that far, please consider it! Closing now as there is a fairly acceptable answer :)

Please re-open if you do not feel the question has been answered sufficiently.

**Closed by Anthropic** 2016-04-11 09:23 UTC
Labels: type: discussion, ui: add-on

**Comment by milanpatel-parkstreet** [comment] 2018-06-26 11:57
Hi @brettahale 
We have use uib-datepicker-popup but the issue is data not bind in a model.
It would be great to provide ready add-on.
