### ISSUE TITLE
Provide more useful error than "Invalid type, expected array"

### ISSUE THREAD

**Issue by upq** [json-schema-form/angular-schema-form#625] opened 2016-01-10 13:45 UTC
I get this error while the output is exactly how I expect it, the problem is that the form is invalid.
### Form

``` javascript
form =    {
                                        "key": "data.answers",
                                        "type": "array",
                                        "items": [
                                            {
                                                "key": "data.answers[]",

                                                "items": [
                                                    {
                                                        "key": "data.answers[].text",
                                                        "type": "text",
                                                        "title": "Question",
                                                    },
                                                ]
                                            }
                                        ]
                                    },
```
### Schema

``` javascript

        scope.schema = {
                        "type": "object",
                        "title": "Types",
                        "properties": {
                            "data": {
                                "type": "object",
                                "title": "data",
                                "properties": {
                                    "answers": {
                                        "type": "array",
                                        "title":"Answers",
                                        "default": [],
                                        "items": {
                                            "type": "object",
                                            "title": "Answer",
                                            "properties": {
                                                "text": {
                                                    "title": "Answer",
                                                    "type": "text",
                                                    "required": true,
                                                },
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    };
```
### expected output

data = {answers: [{text: "answer1"}, {text: "answer2"}], correct: 1, question: "questioning?"}

Now the expected output is right but the form is invalid saying that it expected an array, anything Im missing here?

**Comment by toomuchdesign** [comment] 2016-01-16 17:06
Same problem here. The validation error (*Invalid type, expected array*) appears when adding a second item into an array field.

It seems to be a problem related to **angular-schema-form-bootstrap**. I have no troubles when using the old decorators included in ASF folder.

This is my current setup:
- angular 1.4.8
- angular-schema-form 0.8.12
- angular-schema-form-bootstrap 0.2.0

I'm going to investigate on this in the next days and set up a plunkr if needed.
Any hint would be great!

**Comment by toomuchdesign** [comment] 2016-01-16 18:21
@upq back to your example: are you sure about setting "type" properties to "text"?

I suppose the correct type for your text items in Schema declaration should be "string" ;-)

```
"text": {
    "title": "Answer",
    "type": "string",
    ...
}
````

**Comment by toomuchdesign** [comment] 2016-01-16 18:32
Meanwhile I found an acceptable solution.

I had the validation issue when trying to get an **array of textarea-strings**:
```
[ "Lorem ispsum", "Lorem ispsum", "Lorem ispsum",]
```
I was able to overtake the validation issue by setting the field up as an **array of objects** as described in the [demo](http://schemaform.io/examples/bootstrap-example.html#/ce1076e82a119133ebd6):
```
[ { "text": "Lorem ispsum" }, { "text": "Lorem ispsum" }, { "text": "Lorem ispsum" }]
```

**Comment by upq** [comment] 2016-01-16 23:30
@toomuchdesign changing the type to string actually worked!

**Comment by jugglingcats** [comment] 2016-01-27 11:39
I'm not sure this should have been closed. While @upq had a typo in his schema, @toomuchdesign did not and had to use a workaround that changed the schema.

We have the following schema fragment:
```json
                    "features" : {
                        "type" : "array",
                        "title" : "Features",
                        "items" : {
                            "type" : "string",
                            "required" :true
                        }
                    }
```
This works fine with the old decorator but breaks with the new one giving the on-screen error described. We can't easily use the workaround as the documents already created follow the schema above.

**Comment by Anthropic** [comment] 2016-02-16 02:18
I have recently had the same issue but it was due to the data returned from the server changing null to empty string on a field, but rather than show a useful error, I got the above. Suffice to say it took some time to determine that the returned string was failing the array item as it was defined as being an integer value. I think we need to look at improving the feedback on this one.

**Comment by toomuchdesign** [comment] 2016-02-16 09:22
@Anthropic, I confirm your issue: empty strings values returned by the server breaking the validation. I ended up with iterating the returned data object and removing empty values before sending data to the server.

**Comment by edi9999** [comment] 2016-05-20 15:53
I've got the same issue, but with valid input . Here is my code : 

```
angular.module('my_app')
.controller('FoobarController', function($scope) {
    $scope.schema = {
        type: "object",
        properties: {
            "install_packages": {
                "items": {
                    "type": "string"
                },
                "type": "array"
            },
            "install_groups": {
                "items": {
                    "type": "string"
                },
                "type": "array"
            },
        }
  };


  $scope.form = [
    "*",
    {
      type: "submit",
      title: "Save"
    }
  ];

  $scope.model = {};
});
```

and in my view : 

```
<div ng-controller="FoobarController">
    <form sf-schema="schema" sf-form="form" sf-model="model"></form>
</div>
```

Now if I fill in the two arrays with multiple text elements, I get the error message : `"Invalid type, expected array"`

**Comment by edi9999** [comment] 2016-05-20 15:56
This is very strange, since if I set the model to : 

`$scope.model = {"install_packages":["ewfwef","ewfwe"],"install_groups":["dsafasdf","asdf"]}`

However, If I do the same thing manually, the error appears.

**Comment by Anthropic** [comment] 2016-05-22 13:59
@edi9999 it isn't strange at all it matches exactly what was described in the thread above your comments. If you set it to empty to start with it errors. You cannot reset it, too late. This needs work to fix.

**Comment by edi9999** [comment] 2016-05-23 07:37
https://meet.pclm.altair.com/sshproblem

**Comment by edi9999** [comment] 2016-05-24 14:26
I was able to get rid of the issue by not using : `angular-schema-form-bootstrap 0.2.0`, but instead use the one that is in the dist folder of this repository (when you use npm or bower)

**Comment by Anthropic** [comment] 2016-05-25 01:06
@edi9999 thanks for the info :)

**Comment by donalmurtagh** [comment] 2017-02-23 16:16
I also get this issue when I use `angular-schema-form-bootstrap 0.2.0` with `angular-schema-form  0.8.13`. Here's a [plunker demo](https://plnkr.co/edit/JBDUMFos47aF39KkMDqF?p=preview). As soon as you add one item to the array you get the field error "Invalid type, expected array" is displayed.

**Comment by Anthropic** [comment] 2017-02-26 15:12
@donalmurtagh I have a fix for that based on comments in #649, will get it out in alpha.3 this week, should have in dev branch in the next day or two I hope.

**Comment by donalmurtagh** [comment] 2017-02-27 19:45
@Anthropic Great, I'll try that out alpha3 as soon as it's available. It would really be appreciated if you could mention in the release notes of alpha3 which version of the bootstrap decorator it should be used with.

**Comment by mark007** [comment] 2017-03-21 13:02
Hi, Id be interested to see your fix for this in alpha 3 also Anthropic. Is a patch already merged for the fix?

**Comment by Anthropic** [comment] 2017-03-22 01:12
@mark007 due to family emergency I haven't gotten alpha 3 out yet, I am hoping to get something out this weekend if everything lines up for me.

**Comment by mark007** [comment] 2017-03-22 08:37
Thanks Anthropic. In general is there a list of features in lets say json schema draft 4, that asf currently does / doesn't support? I couldn't see any particular list on the github pages themselves, ie whether theres support for validation of things like string types with particular formats, like ipv4 etc. From searching the code I assume things like that aren't in there currently, but just wanted to know was there a place to go to see what is / isn't in there. Its a great project, we would love to contribute to it when we get more familiar with its workings.

**Comment by mark007** [comment] 2017-04-04 13:14
Can I just confirm guys, that this issue, is different to this other one ( #750  ) one that has had fixes pushed up for it https://github.com/json-schema-form/angular-schema-form/issues/750

**Comment by Anthropic** [comment] 2017-04-04 13:33
@mark007 It is different, I believe, but I do believe that this issue is fixed by either alpha 3 already or 4 in dev branch. I can't change the error message which comes from tv4, but at least now when you change the value it should remove the error and it should display only when it is accurate.

**Comment by mark007** [comment] 2017-04-04 13:40
Thanks Anthropic. Thats why I wasn't sure, in my bower.json I'm pulling down todays latest push for angular-schema-form-bootstrap, but on page load, under my array field I still see the error appearing, even after I fill in the individual array items to make them valid.

Do you think I should put together an example or is it easy to also see this on your end. I'm using angular 1.6.4. This is a snippet of what I have in my schema incase you wanted to try.

"ntp_external_servers": {
  "type": "array",
  "items": {
    "type": "string"
  },
  "minItems": 1,
  "default": ["1.2.3.4"]
}

**Comment by Anthropic** [comment] 2017-04-04 13:43
If you use the example and make a gist with a schema and form definition I can load that on the latest version locally and debug. Which versions is bower pulling down?

**Comment by mark007** [comment] 2017-04-04 13:59
Bower sees alpha 3 of angular schema form bootstrap, not an alpha 4 so I use the actual git commit id to get the absolute latest. I'm not sure how to change the versions in the gist link, to use angular schema form bootstrap latest, but even this example should show the issue, if the latest version is used.

http://schemaform.io/examples/bootstrap-example.html#/d127f6b978d7dff299afe010e91c2ea8

**Comment by EtiAggarwal** [comment] 2017-04-13 13:58
I still see the issue on alpha 3 when using array of strings

**Comment by Anthropic** [comment] 2017-04-14 16:48
@EtiAggarwal @mark007 to be clearer, the main thing I fixed was that once the error appeared you couldn't get rid of it, to fix this entire issue I have updated ASF just now to put in an empty string instead of null, it will be in the next alpha update or you can try the version in the dev branch.

**Closed** 2017-04-15 10:11 UTC
Labels: needs: PR, status: ready to release, type: enhancement

**Comment by mark007** [comment] 2017-04-18 07:49
Thanks Anthropic, I can't seem to pick it up yet using the schema form bootstrap bundled min file. I guess its not merged yet, I will pick it up once its there.

Thanks again.

**Comment by Anthropic** [comment] 2017-04-18 12:42
@mark007 it should be, what version of the file are you using, what's the version headers say?

**Comment by mark007** [comment] 2017-04-18 12:50
This is from the header of the bundled asf bootstrap file, looks like it was just built yesterday.

/*!
 * angular-schema-form-bootstrap
 * @version 1.0.0-alpha.4
 * @date Mon, 17 Apr 2017 08:57:43 GMT

I still have the issue if I don't set all of the array fields to [] before passing to the form, the error is appearing for me. Whats the easiest way to reproduce this for you. gist doesn't seem to have the ability to let me pick the exact version of the ASF bootstrap.

I wonder did the bundled bootstrap one get the fix merged in from the other repo.

**Comment by Anthropic** [comment] 2017-04-18 13:05
@mark007 plunkers are the best method @warmy1004 has made some great ones, he bothered to put in multiple versions so you can compare, try this one and modify how you like the one thing I would ask is that you make sure the schema and form definition are json compatible and not js or I have to go and add quote on all the properties if I want to test it in my local test instance :)

**Comment by Tarjei400** [comment] 2017-07-10 07:27
Hi I took a liberty to tweak this example and to show there still is issue with[https://plnkr.co/edit/RBQBHEUJAfOnYYpcHPnP?p=preview](url) Invalid type, expected array.

**Comment by Tarjei400** [comment] 2017-07-10 08:11
It seems like the parent form isnt updated when sub item changes. If I add a requirement on a string in items array like maxLength: 5 it gets wierder even more

**Comment by Anthropic** [comment] 2017-07-16 14:31
@Tarjei400 that's using alpha.2 the current one is alpha.4 and dev branch is a little ahead of that already.
