### ISSUE TITLE
Boolean fields in the view default to “false” when form and schema are set from within $http.get()

### ISSUE THREAD

**Issue by mutharasus** [json-schema-form/angular-schema-form#611] opened 2015-11-30 17:09 UTC
I posted a detailed question in stackoverflow with JSFiddle examples:
http://stackoverflow.com/questions/33963976/boolean-fields-in-the-view-default-to-false-when-scope-form-and-scope-schema

**Comment by Anthropic** [comment] 2016-04-15 11:50
@mutharasus I'm new to the project, can you check/update the JSFiddles, perhaps the URLs to this repo are different so they aren't loading now for me. If you do that I will take a look at what is happening.

**Comment by slyadams** [comment] 2016-11-25 09:30
I'm also having this issue. I'm writing a 'bulk edit' form where I create a checkbox for each form field to enable modifying of that field. I then use a watcher to copy the fields (and not the enabling checkboxes) into the binding value of my directive. The problem is that these forced defaults is setting all my checkboxes to false.

**Comment by Anthropic** [comment] 2017-04-23 14:52
@slyadams 
I believe this is fixed in the latest updates (alphas) for the eventual 1.0.0 release.

Please re-open if there are still issues in these versions.

**Comment by Anthropic** [comment] 2017-04-23 14:53
If anyone wants this re-opened I need a gist or plunker please.

**Closed by Anthropic** 2017-04-23 14:52 UTC
Labels: needs: demo (gist / plunker), type: question
